In [1]:
import pandas as pd
import numpy as np

In [2]:
lincs_1000_path = "./curated/LINCS-Pilot1/L1000/replicate_level_l1k.parquet"
lincs_cp_path = "./curated/LINCS-Pilot1/CellPainting/replicate_level_cp_augmented.parquet"

bray_l1000_path = "./curated/CDRP-BBBC047-Bray/L1000/replicate_level_l1k.parquet"
bray_cp_path = "./curated/CDRP-BBBC047-Bray/CellPainting/replicate_level_cp_augmented.parquet"

caicedo_l1000_path = "./curated/LUAD-BBBC041-Caicedo/L1000/replicate_level_l1k.parquet"
caicedo_cp_path = "./curated/LUAD-BBBC041-Caicedo/CellPainting/replicate_level_cp_augmented.parquet"

rohban_l1000_path = "./curated/TA-ORF-BBBC037-Rohban/L1000/replicate_level_l1k.parquet"
rohban_cp_path = "./curated/TA-ORF-BBBC037-Rohban/CellPainting/replicate_level_cp_augmented.parquet"

In [3]:
l1000_genes = pd.read_excel("./idmap.xlsx")
l1000_map = {k:v for k,v in zip(l1000_genes["probe_id"], l1000_genes["symbol"])}

In [4]:
for i in [lincs_1000_path, bray_l1000_path, caicedo_l1000_path, rohban_l1000_path]:
    curr_df = pd.read_parquet(i)
    curr_df = curr_df.rename(columns=l1000_map)
    curr_df.to_parquet(i)

In [5]:
lincs_l1000 = pd.read_parquet(lincs_1000_path)
lincs_cp = pd.read_parquet(lincs_cp_path)

bray_l1000 = pd.read_parquet(bray_l1000_path)
bray_cp = pd.read_parquet(bray_cp_path)

caicedo_l1000 = pd.read_parquet(caicedo_l1000_path)
caicedo_cp = pd.read_parquet(caicedo_cp_path)

rohban_l1000 = pd.read_parquet(rohban_l1000_path)
rohban_cp = pd.read_parquet(rohban_cp_path)

In [6]:
# from curate_dataset.ipynb
# common_l1000_meta = ['Metadata_Plate', 'Metadata_cell_id', 'Metadata_pert_id', 'Metadata_pert_timepoint']
# common_cp_meta = ['Metadata_Plate', 'Metadata_Plate_Map_Name', 'Metadata_Well', 'Metadata_cell_id', 'Metadata_pert_id', 'Metadata_pert_timepoint', 'Metadata_pert_type']
# common_all_meta = ['Metadata_Plate', 'Metadata_cell_id', 'Metadata_pert_id', 'Metadata_pert_timepoint']

In [7]:
# from curate_dataset.ipynb
# TA-ORF-BBBC037-Rohban cp does not correctly identify Metadata_pert_type, because it marks all as trt.
# caicedo_cp["Metadata_pert_type"].unique()
# rohban_cp["Metadata_pert_type"].unique()
# rohban_cp["Metadata_pert_id"][rohban_cp["Metadata_pert_id"].str.contains("con")].unique()
rohban_cp.loc[rohban_cp["Metadata_pert_id"] == "negcon", "Metadata_pert_type"] = "control"
rohban_cp.to_parquet(rohban_cp_path)
rohban_cp = pd.read_parquet(rohban_cp_path)

In [18]:
# checking correct Metadata_pert_type annotation for rohban in l1000
# negcon is TRCN0000000000
rohban_l1000[rohban_l1000["Metadata_pert_type"] == "control"]["Metadata_pert_id"].unique()

array(['TRCN0000000000'], dtype=object)

#### LINCS data

In [19]:
lincs_l1000.head()

,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_pert_dose_micromolar,Metadata_cell_id,Metadata_pert_iname,Metadata_ARP_ID,Metadata_pert_timepoint,Metadata_SMILES,...,CCP110,STK10,UGDH,SQOR,HEBP1,ATP11B,CD320,MLLT11,CEBPZ,CBR3
0,REP.A001_A549_24H_X1_B27,A03,-666,control,-666.0,A549,DMSO,AB00016884,24,-666,...,-0.1345,-0.1423,0.1349,0.3684,-3.1025,-0.6226,-3.7452,-1.3157,1.0145,0.1046
1,REP.A001_A549_24H_X1_B27,A04,-666,control,-666.0,A549,DMSO,AB00016884,24,-666,...,0.5892,3.2737,-15.1256,0.5294,-0.6672,3.7304,0.6153,-1.4900,0.9750,-1.8243
2,REP.A001_A549_24H_X1_B27,A05,-666,control,-666.0,A549,DMSO,AB00016884,24,-666,...,-0.2690,-1.0745,0.1349,-0.1003,-2.3632,-0.2763,0.4857,0.1338,-0.2992,1.1796
3,REP.A001_A549_24H_X1_B27,A06,-666,control,-666.0,A549,DMSO,AB00016884,24,-666,...,-0.5354,-0.9029,-15.0048,-0.2428,0.0595,-0.1896,0.8919,-1.2058,-0.2843,0.2155
4,REP.A001_A549_24H_X1_B27,A07,BRD-K25114078-003-08-1,trt,10.0,A549,aminoguanidine,AB00016884,24,NNC(N)=N,...,-0.6069,0.3590,-15.3090,-0.0670,-0.7765,-0.3680,0.9602,-1.4851,-0.3904,-0.3328

In [20]:
lincs_cp.head()

,Metadata_Plate_Map_Name,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_pert_dose_micromolar,Metadata_cell_id,Metadata_pert_iname,Cells_AreaShape_Area,Cells_AreaShape_Center_X,...,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_20_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_20_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_20_0,Nuclei_Texture_Variance_RNA_5_0,Metadata_pert_timepoint
0,C-7161-01-LM6-018,SQ00015202,A01,DMSO,control,0.0,A549,None,11078.0,1137.0,...,1.7175,1.5656,1.8454,1.3640,1.1847,1.4895,2.5998,2.4852,2.5960,48
1,C-7161-01-LM6-018,SQ00015202,A02,DMSO,control,0.0,A549,None,12067.0,1163.0,...,1.6896,1.5570,1.8082,1.2829,1.1663,1.4433,2.6393,2.5176,2.6293,48
2,C-7161-01-LM6-018,SQ00015202,A03,DMSO,control,0.0,A549,None,11303.0,1096.0,...,1.6843,1.5106,1.8164,1.2761,1.1449,1.4160,2.6129,2.4979,2.6255,48
3,C-7161-01-LM6-018,SQ00015202,A04,DMSO,control,0.0,A549,None,11350.0,987.0,...,1.5769,1.3750,1.7435,1.3635,1.1904,1.5205,2.6556,2.5231,2.6443,48
4,C-7161-01-LM6-018,SQ00015202,A05,DMSO,control,0.0,A549,None,11180.0,1147.0,...,1.6596,1.5557,1.7396,1.4016,1.2707,1.5275,2.6863,2.6061,2.6734,48

#### Bray data

In [21]:
bray_l1000.head()

,Metadata_Plate,Metadata_pert_id,Metadata_pert_iname,Metadata_pert_dose_micromolar,Metadata_cdrp_group,Metadata_SMILES,COQ3,CREB3L2,CISD1,VDAC1,...,ASL,MLLT11,CEBPZ,PRKACA,ASAP2,CLASRP,CBR3,LYRM1,Metadata_cell_id,Metadata_pert_timepoint
0,PAC001_U2OS_6H_X1_B1_UNI4445L,BRD-K07762753-001-03-6,aminopurvalanol A,50.0,BIO,CC(C)[C@H](CO)Nc1nc(Nc2cc(N)cc(Cl)c2)c2ncn(C(C...,-0.118505,-0.293445,-0.294088,0.292745,...,0.430269,-0.97559,-1.740605,0.340382,0.498778,0.352152,0.53591,0.52484,U2OS,6
1,PAC001_U2OS_6H_X1_B1_UNI4445L,BRD-K09991945-001-02-0,GSK-3 inhibitor II,12.7,BIO,Ic1cccc(CSc2nnc(o2)-c2ccncc2)c1,0.043264,-0.264945,-0.000633,0.000935,...,0.556969,0.25051,-0.025625,-0.024428,-0.225122,0.533052,-0.19329,-0.25436,U2OS,6
2,PAC001_U2OS_6H_X1_B1_UNI4445L,BRD-K46678324-001-03-7,RHO-kinase inhibitor II,50.0,BIO,Clc1cc(Cl)c(NC(=O)Nc2ccncc2)c(Cl)c1,-0.070805,0.195755,0.004606,-0.040855,...,-0.017741,0.05681,0.130695,0.005919,-0.408722,-0.057177,-0.25699,0.31004,U2OS,6
3,PAC001_U2OS_6H_X1_B1_UNI4445L,BRD-K67860401-001-02-3,GSK-3beta inhibitor VIII,16.2,BIO,COc1ccc(CNC(=O)Nc2ncc(s2)[N+]([O-])=O)cc1,0.027165,-0.149545,0.173113,-0.100695,...,0.219869,-0.16129,0.365195,-0.040848,-0.251122,0.040732,0.17091,-0.05144,U2OS,6
4,PAC001_U2OS_6H_X1_B1_UNI4445L,BRD-K52620403-001-01-8,STO 609,12.5,BIO,OC(=O)c1ccc2c3nc4ccccc4n3c(=O)c3cccc1c23,0.303294,0.254455,-0.055418,-0.053635,...,0.245469,0.00784,0.093595,-0.303418,0.474878,-0.022947,-0.28589,0.06423,U2OS,6

In [22]:
bray_cp.head()

,Metadata_Plate_Map_Name,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_dose_micromolar,Metadata_pert_type,Metadata_cell_id,Cells_AreaShape_Area,Cells_AreaShape_Center_X,Cells_AreaShape_Center_Y,...,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0,Metadata_pert_timepoint
0,H-BIOA-004-3,24277,A01,BRD-K18250272-003-03-7,6.05,trt,U2OS,2803.0,330.0,258.0,...,1.631313,1.937284,1.812554,1.386521,1.689170,1.547606,2.469984,2.376336,2.402145,48
1,H-BIOA-004-3,24277,A02,BRD-K18316707-001-01-9,10.00,trt,U2OS,2458.0,357.0,257.5,...,1.696021,1.947088,1.897656,1.630578,1.773510,1.740362,2.552390,2.428562,2.458853,48
2,H-BIOA-004-3,24277,A03,BRD-K18438502-001-02-6,10.00,trt,U2OS,2321.0,315.5,229.5,...,1.888156,2.060230,2.003572,1.730377,1.856694,1.799151,2.506932,2.431198,2.479527,48
3,H-BIOA-004-3,24277,A04,BRD-K18550767-001-02-8,10.00,trt,U2OS,2867.0,270.5,267.0,...,1.854028,2.043121,1.994476,1.752150,1.788835,1.788962,2.665640,2.529105,2.598130,48
4,H-BIOA-004-3,24277,A05,BRD-K18574842-323-03-3,4.39,trt,U2OS,2969.0,335.5,279.0,...,1.914947,2.237998,2.135490,1.697586,1.899021,1.844055,2.753912,2.590156,2.649836,48

#### Caicedo data

In [23]:
caicedo_l1000.head()

,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_cell_id,Metadata_ARP_ID,Metadata_pert_timepoint,Metadata_transcriptdb,AARS1,ABCB6,...,ZMIZ1,ZMYM2,ZNF131,ZNF274,ZNF318,ZNF395,ZNF451,ZNF586,ZNF589,ZW10
0,TA.OE014_A549_96H_X1_B19,H04,BRDN0000552648,trt,A549,DOC45.46.47.48.A,96,NM_000455.4:c.166G>T,0.9351,-0.7092,...,-0.0944,0.7810,1.4026,-0.0342,-1.1816,0.0377,0.0000,0.0388,-0.1474,-0.7273
1,TA.OE014_A549_96H_X2_B19,H04,BRDN0000552648,trt,A549,DOC45.46.47.48.A,96,NM_000455.4:c.166G>T,0.1938,-0.8948,...,1.3418,-0.4040,-0.3374,-0.3401,0.1351,-0.1123,-0.2336,0.9676,7.7144,0.0718
2,TA.OE014_A549_96H_X3_B19,H04,BRDN0000552648,trt,A549,DOC45.46.47.48.A,96,NM_000455.4:c.166G>T,-0.1961,-0.1821,...,0.0935,-1.0599,0.9036,3.7128,0.8236,1.0865,0.0838,2.1439,0.9606,0.1927
3,TA.OE014_A549_96H_X4_B19,H04,BRDN0000552648,trt,A549,DOC45.46.47.48.A,96,NM_000455.4:c.166G>T,-0.0667,-0.6642,...,-0.7749,-0.4752,0.1437,0.2395,-0.5959,-0.1953,0.6105,0.4223,-0.3854,0.6411
4,TA.OE014_A549_96H_X5_B19,H04,BRDN0000552648,trt,A549,DOC45.46.47.48.A,96,NM_000455.4:c.166G>T,0.8557,-0.1338,...,0.7920,0.6814,0.7776,1.0793,-0.9001,-1.3934,-0.6889,-0.0760,0.3536,0.2316

In [24]:
caicedo_cp.head()

,Metadata_Plate_Map_Name,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_cell_id,Metadata_genesymbol_mutation,Metadata_genesymbol,Cells_AreaShape_Area,Cells_AreaShape_Center_X,...,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0,Metadata_pert_timepoint
0,DOC45.46.47.48,52657,A01,EMPTY,control,A549,negcon,None,2139.5,555.0,...,1.659822,1.889509,1.845729,1.528695,1.637885,1.598239,2.676074,2.766497,2.843282,96
1,DOC45.46.47.48,52665,A01,EMPTY,control,A549,negcon,None,2592.0,544.0,...,2.036738,2.293261,2.247582,1.804211,1.957284,1.907834,2.860178,2.876078,2.903756,96
2,DOC45.46.47.48,52653,A01,EMPTY,control,A549,negcon,None,2345.0,581.0,...,1.581156,1.846026,1.796802,1.450832,1.574195,1.533081,2.576752,2.715917,2.794145,96
3,DOC45.46.47.48,52663,A01,EMPTY,control,A549,negcon,None,2175.0,553.0,...,1.548594,1.823283,1.784059,1.476419,1.608301,1.567274,2.629259,2.777180,2.855192,96
4,DOC45.46.47.48,52649,A01,EMPTY,control,A549,negcon,None,1986.0,539.0,...,1.694706,1.926785,1.879817,1.486609,1.639697,1.609791,2.721927,2.859684,2.928258,96

#### Rohban data

In [25]:
rohban_l1000.head()

,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_cell_id,Metadata_ARP_ID,Metadata_pert_timepoint,Metadata_genesymbol_mutation,PSME1,CISD1,...,NCOA3,CDKN1B,POLD4,FOSL1,MLLT11,CEBPZ,PRKACA,GAPDH,CBR3,LYRM1
0,TA.OE005_U2OS_72H_X1_B15,A03,BRDN0000398935,trt,U2OS,DOA60.61.62.63.A,72,ATF4,0.1206,-1.5736,...,0.7331,-4.6611,5.2998,-1.8623,1.0967,0.1248,1.9399,-2.3944,-0.6060,1.4767
1,TA.OE005_U2OS_72H_X1_B15,A04,BRDN0000462377,trt,U2OS,DOA60.61.62.63.A,72,TSC2,-0.7540,-3.0963,...,1.1580,-2.2099,0.5853,-1.1206,0.9088,1.4177,-0.6254,0.0000,-0.2817,0.3531
2,TA.OE005_U2OS_72H_X1_B15,A05,BRDN0000402765,trt,U2OS,DOA60.61.62.63.A,72,BAX,0.7575,-0.5961,...,0.9813,-0.9327,-0.7194,-0.1297,-0.8636,-0.1319,0.8658,0.0000,-0.3569,0.5284
3,TA.OE005_U2OS_72H_X1_B15,A06,BRDN0000403526,trt,U2OS,DOA60.61.62.63.A,72,VEGFC,-1.6981,-0.5644,...,-0.0157,-0.4220,-0.4333,0.0276,-0.6675,0.8938,-1.0765,0.0000,1.0729,-2.2821
4,TA.OE005_U2OS_72H_X1_B15,A07,BRDN0000408131,trt,U2OS,DOA60.61.62.63.A,72,CCND1,-1.5586,0.7878,...,-0.6599,-1.0454,-1.1190,-0.5694,1.1907,0.9852,-1.1061,0.0000,0.9646,-2.1794

In [26]:
rohban_cp.head()

,Metadata_Plate_Map_Name,Metadata_Plate,Metadata_Well,Metadata_pert_id,Metadata_pert_type,Metadata_cell_id,Metadata_genesymbol_mutation,Metadata_genesymbol,Cells_AreaShape_Area,Cells_AreaShape_Center_X,...,Nuclei_Texture_Variance_ER_10_0,Nuclei_Texture_Variance_ER_3_0,Nuclei_Texture_Variance_ER_5_0,Nuclei_Texture_Variance_Mito_10_0,Nuclei_Texture_Variance_Mito_3_0,Nuclei_Texture_Variance_Mito_5_0,Nuclei_Texture_Variance_RNA_10_0,Nuclei_Texture_Variance_RNA_3_0,Nuclei_Texture_Variance_RNA_5_0,Metadata_pert_timepoint
0,TAORF_REFERENCE_SET,41744,A01,negcon,control,U2OS,EMPTY_,EMPTY,4138.0,569.0,...,1.440687,1.506719,1.484461,1.245067,1.300214,1.250547,2.549217,2.549292,2.580768,72
1,TAORF_REFERENCE_SET,41744,A02,negcon,control,U2OS,EMPTY_,EMPTY,4362.0,576.5,...,1.515587,1.529815,1.523954,1.304125,1.409949,1.357492,2.565789,2.571296,2.606567,72
2,TAORF_REFERENCE_SET,41744,A03,ccsbBroad304_00117,trt,U2OS,ATF4_WT.1,ATF4,4180.0,577.5,...,1.516549,1.478524,1.460322,1.375558,1.413097,1.415326,2.575652,2.621210,2.668294,72
3,TAORF_REFERENCE_SET,41744,A04,ccsbBroad304_07101,trt,U2OS,TSC2_WT,TSC2,4435.0,549.0,...,1.407649,1.492252,1.454440,1.299621,1.330510,1.304007,2.595669,2.626601,2.649400,72
4,TAORF_REFERENCE_SET,41744,A05,ccsbBroad304_00150,trt,U2OS,BAX_WT,BAX,4223.0,519.5,...,1.438448,1.444328,1.422024,1.343384,1.410478,1.379160,2.615251,2.654130,2.695320,72